name: Kufar Parser

on:
  schedule:
    - cron: "0 */3 * * *"  # Каждые 3 часа
  workflow_dispatch:  # Ручной запуск

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" > .env
        echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> .env

    - name: Run parser
      run: python main.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add noutbuki.xlsx data.json
        git commit -m "Auto-update data files" || echo "No changes to commit"
        git push